2022-12-19 17:51:37.315 +02:00 [ERR] Error: {"ClassName":"System.Exception","Message":null,"Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at SpendLess.UnitTests.Tests.<>c.<<TaskMethodsWithExceptionsAreLoggedByInterceptor>b__32_0>d.MoveNext() in C:\\Users\\viliu\\Documents\\GitHub\\SpendLess\\SpendLess\\UnitTests\\Tests.cs:line 245\r\n--- End of stack trace from previous location ---\r\n   at SpendLess.Server.Interceptor.UnhandledExceptionLogger.InterceptAsync(Task task) in C:\\Users\\viliu\\Documents\\GitHub\\SpendLess\\SpendLess\\Server\\Interceptor\\UnhandledExceptionLogger.cs:line 49","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146233088,"Source":"Tests","WatsonBuckets":null}
